name: run Fiis_23.py

on: workflow_dispatch

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar python
        uses: actions/setup-python@v3

      - name: instalar Selenium
        run: pip install selenium

      - name: instalar web driver
        run: pip install webdriver-manager

      - name: instalar Pandas
        run: pip install pandas
      
      - name: Google Api
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      

      # - name: instalar os todos os pacotes
      #   run: pip install -r requirements.txt
       

      - name: executar arquivo de scrapping
        run: python Fiis_23.py