name: run Fiis_23.py

on:
  schedule:
    - cron: '5 3 * * *'

  push:
    branches:
      - "fix/navegador-docker"

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sobe o container do navegador
        run: docker compose up -d

      - name: instalar python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: instalar os todos os pacotes
        run: pip install -r requirements.txt

      - name: Verifica container de pe
        run: docker ps

      - name: executar arquivo de scrapping
        run: python Fiis_23.py
